apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-raf
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 80
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: nginx
         image: nginx
         ports:
         - containerPort: 80
