---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-111-xx
  namespace: 11-example
spec:
  containers:
    - name: myapp-1
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data-x/out1A.txt; sleep 300; done",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data-x
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: myapp
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-222-xx
  namespace: 11-example
spec:
  containers:
    - name: myapp-2
      image: busybox
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data-x/out1A.txt; sleep 300; done",
        ]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data-x
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: myapp

# kubectl -n 11-example get pvc|c
